### ISSUE TITLE
Enable visual-grid

### ISSUE THREAD

**Issue by alexkerber** [smutek/BourbonySage#1]
Any good approach to enable $visual-grid: true; with your setup? Otherwise, great work! :+1:

**Comment by smutek** [comment]
Hey @alexkerber - glad you like it!

Visual grid is added to the most recent version. See [a9186d0](https://github.com/smutek/BourbonySage/commit/a9186d03d09bcd6d8d42ec0109c3642a97f98001).

If you are using this on a current project, just turn on the grid in the _variables.scss file with `$visual-grid: true;` and move the grid variables from _grid to _variables - at the very least the `$max-width` variable needs to be defined in the variables file so the visual grid width will match the width of the site.

For example - in _variables.scss, just adding these 2 definitions should get you up and running. 

```
$visual-grid: true;
$max-width: 1170px;
```

I did the extra re-structuring because it seemed to make more sense.

Hope this helps!
