### ISSUE TITLE
Gulp error: "No mixin named make-sm-column"

### ISSUE THREAD

**Issue by matteogalli** [smutek/BourbonySage#2]
Hi, after 1.1 update, I see this error when running Gulp: "_no mixin named make-sm-column_".
File interested is `assets/styles/components/_grid.scss`.

I do not understand how it should be used `_grid.scss`, can you help me understand?
What's the difference with what is written on `_layout.scss`?
Variables `$main-sm-columns` and `$sidebar-sm-columns`, and mixin `make-sm-column` must be defined in `_variables.scss`?

Thank you!!

**Comment by smutek** [comment]
@playcodestudio - 

`_grid.scss` should not be there. I accidentally re-included this file when I merged the most recent commit from the master Sage branch. I'm going to have to find a better way to keep this fork up to date with Sage master, for now I think doing it manually is going to be the way to go, in order to avoid mistakes like this one.  

For your current project, I would just delete the `_grid.scss` file, or you can download the most recent commit.

The grid settings for this project are in `_layout.scss`, with the associated variables definitions in `_variables.scss` - see [a9186d0](https://github.com/smutek/BourbonySage/commit/a9186d03d09bcd6d8d42ec0109c3642a97f98001)

Thanks very much for pointing this out. I just pushed a commit which removes `_grid.scss`. I'm going to mark this as closed, please re-open if I've missed anything.
